import Head from 'next/head'
import styles from '../styles/Home.module.css'
import axios from 'axios'
import { useState } from 'react'
export default function Home() {
  const [data, setData] = useState('');
  const [location, setLocation] = useState('')
  const [weather, setWeather] = useState ('')
  const [main, setMain] = useState ('')
  const [wind, setWind] = useState ('')
  const [errorMessage, setErrorMessage] = useState('')

  var apiKey = "da099f872aba6423e0b2426fadaa778b"
  var lang = "Een"
  var units = "metric"
  const url = `https://api.openweathermap.org/data/2.5/weather?q=${location}&units=${units}&appid=${apiKey}&lang=${lang}`

  const searchLocation = (event => {
    if(event.key == "Enter"){
      axios.get(url)
      .then((response) => {
        console.clear();
        setData(response.data)
        console.log(response.data)
        setWeather(response.data.weather)
        setMain(response.data.main)
        setWind(response.data.wind)
        setErrorMessage("")
      }).catch(err => {
        console.log(err)
        setErrorMessage("Please enter another location")
        setData({})
        setWeather()
        setMain()
        setWind()
      })
    }
  })

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com"></link>
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin></link>
        <link href="https://fonts.googleapis.com/css2?family=Laila:wght@600&family=PT+Serif:wght@700&family=Prompt&family=Righteous&family=Signika:wght@500&display=swap" rel="stylesheet"></link>
      </Head>
      
      <div className={styles.header}>Todays Weather</div>
      <div className={styles.subhead}>Type in the location you want to check the weather of</div>
      <div className={styles.inputs}>
        <input className={styles.input}
          value={location}
          onChange={event => setLocation(event.target.value)}
          placeholder="Enter location"
          onKeyDown={searchLocation}
          type="text"
        />
      </div>

      <main className={styles.main}>
        {errorMessage}
        <div className={styles.location}>{data.name}</div>
        {
          weather && weather.map((w, index) => {
            return(
              <div key={index}>
                <div className={styles.name}>Temperature</div> 
                  <div className={styles.temp}>{main.temp}°C</div>
                <div className={styles.name}>Feels Like</div> 
                  <div className={styles.temp}>{main.feels_like}°C</div>
                <div className={styles.name}>Description</div> 
                  <div className={styles.desc}>{w.description}</div>
                <div className={styles.name}>Wind Gust</div> 
                  <div className={styles.wind}>{wind.gust} m/s</div>
              </div>
            )
          })
        }
      </main>
    </div>
  )
}


